#!/bin/bash

echo "====================================="
echo "	  Ubuntu Master Tools Installer    "   
echo "====================================="

echo "Rollback Unity Desktop To Metacity"
sudo apt-get install gnome-session-flashback

echo "Installing Basic Packages"
sudo apt-get -y install git nmap ftpd openssh-server virtualbox calibra bacula filezilla wireshark thunderbird 

echo "Installing Terminals"
sudo apt-get -y install konsole
sudo apt-get -y install terminator
sudo apt-get -y install yakuake

echo "Installing BlueTooth"
sudo apt-get -y install bluez
sudo apt-get -y install bluez-firmware
sudo apt-get -y install bluetooth
sudo apt-get -y install blueman
sudo apt-get -y install bluez-tools

echo "Installing System Package Managers"
sudo apt-get -y install nautilus
sudo apt-get -y install synaptic

echo "Installing Servers"
sudo apt-get install -y apache2;
sudo apt-get install -y putty;
sudo apt-get install -y sshd;

echo "Installing Gimp"
sudo apt-get install -y gimp;

echo "Audio Production Packages"
sudo apt-get install -y mixxx;
sudo apt-get install -y audacity;
sudo apt-get install -y winff;

echo "Network Security Packages"
sudo apt-get install -y hydra;
sudo apt-get install -y snort;
sudo apt-get install -y john;
sudo apt-get install -y rkhunter
sudo apt-get install -y dsniff;


sudo apt-get update
